const initialState={
    user:{
        userName:'TDLehman',
        name:
            {
                first:'Tylor',
                last:'Lehman'
            },
        pets:{
            Rowan:{
                gender:'female',
                type:'dog',
                breed:'Poodle',
                picture:'https://goo.gl/1XLUvu'
            },
            Luna:{
                gender:'female',
                type:'dog',
                breed:'Husky',
                picture:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyyjpGh-VvqkHz1B9zEZriqZaNm3GAw3DB3b1iP2wvMkvJ47XH'
            }
        },
    },
    visitors:{
        lastRefresh:'04/30/2018',
        LargePark:{
            williabk198:{
                name:{
                    first:'Brandon',
                    last:'Williams'
                },
                pets:{
                    name:'Harley',
                    picture:'https://goo.gl/PPefEQ',
                    gender:'male',
                    breed:'pitbull',
                    type:'dog',
                    park:'large'
                }
            }
        },
        LittlePark:{

        }
    }
}